name: Longen
favicon: null
layout_spectrum: 0.83756
typography_spectrum: 0.22486634808592498
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434343'
    - '#080808'
    - '#c8c8c8'
    - '#fdfdfd'
    - '#858585'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
