name: Longen
favicon: null
layout_spectrum: 0.75178
typography_spectrum: 0.2391
title: Longen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d4c8f4'
    - '#8051c0'
    - '#5f1c9a'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
